main.py
from flask import Flask
from routes.home import home_route
from routes.cliente import cliente_route

#inicialização
app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

#execução
app.run(debug=True)

routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_clientes():
    #lista os clientes
    return render_template('lista_clientes.html', clientes=CLIENTES)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    #inserir os dados do cliente no bd

    data = request.json          #pega os inputs do front-end

    novo_usuario = {
        "id": len(CLIENTES) + 1, #isso torna o id como auto incremento 
        "nome": data['nome'],    #recebe o nome que está locado na variável data
        "email": data['email'],  #recebe o email que está locado na variável data
    }

    CLIENTES.append(novo_usuario)

    return render_template('item_cliente.html', cliente=novo_usuario)


@cliente_route.route('/new')
def form_cliente():
    #formulário para cadastrar um cliente
    return render_template('form_cliente.html')

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    cliente = list(filter(lambda c: c['id'] == cliente_id, CLIENTES))[0]
    return render_template('detalhe_cliente.html', cliente=cliente)

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    #formulario para editar um cliente

    cliente = None
    for c in CLIENTES:
        if c['id'] == cliente_id:
            cliente = c

    return render_template("form_cliente.html", cliente=cliente)

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
    #atualizar as informações de um cliente

    cliente_editado = None

    #obter dados do formulário de edição
    data = request.json

    #obter usuário pelo id
    for c in CLIENTES:
        if c['id'] == cliente_id:
            c['nome'] = data['nome']
            c['email'] = data['email']

            cliente_editado = c

    #editar usuário
    return render_template('item_cliente.html', cliente=cliente_editado)

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):
    #apaga o registro de um cliente
    global CLIENTES
    CLIENTES = [ c for c in CLIENTES if c ['id'] != cliente_id] 

    return {'deleted': 'ok'}

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template("index.html")

templates/detalhe_cliente.html
<ul>
  <li>ID: {{ cliente.id }}</li>
  <li>Nome: {{ cliente.nome }}</li>
  <li>E-mail: {{ cliente.email }}</li>
</ul>

templates/form_cliente.html
<form id="form" class="c-form" 
    {% if cliente %} 
      action="{{ url_for('cliente.atualizar_cliente', cliente_id=cliente.id)}}" 
    {% else %}
      action="{{ url_for('cliente.inserir_cliente')}}" 
    {% endif %} 
    
    method="{% if cliente %}PUT{% else %}POST{% endif %}"

    {% if cliente %}
      c-swap=".cliente-{{cliente.id}}"
    {% else %}
      c-append="#lista_clientes">
    {% endif %}

  <div class="mb-3">
    <label class="form-label">Nome</label>
    <input type="text" class="form-control" name="nome" {% if cliente %}value="{{cliente.nome}}" {% endif %}>
  </div>

  <div class="mb-3">
    <label class="label-target">Email</label>
    <input type="email" class="form-control" name="email" {% if cliente %}value="{{cliente.email}}" {% endif %}>
  </div>

  <button type="submit" class="btn btn-primary">
    {% if cliente %}Salvar{% else %}Criar{% endif %}
  </button>
</form>

templates/index.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gestão de Usuários</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css')}}">
  </head>
  <body>
    
    <div class="container">
    <h1>Gestão de Clientes</h1>

    <!--Formulário de Clientes-->
    <div id="form-cliente" c-container="{{ url_for('cliente.form_cliente')}}"></div>

    <hr>

    <!--Lista de Clientes-->
    <div c-container="{{ url_for('cliente.lista_clientes')}}"></div>
    </div> <!--Fechando a class container-->

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Cliente</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="exibir_cliente"></div>
        </div>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js')}}"></script>
  </body>
</html>

templates/item_cliente.html
<tr class="cliente-{{cliente.id}}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-secondary" 
            c-get="{{url_for('cliente.detalhe_cliente', cliente_id=cliente.id)}}"
            c-target="#exibir_cliente"
            data-bs-toggle="modal" data-bs-target="#exampleModal">
                Ver
        </button>

        <button class="btn btn-primary" 
            c-get="{{url_for('cliente.form_edit_cliente', cliente_id=cliente.id)}}"
            c-target="#form-cliente">
                Editar
        </button>

        <button class="btn btn-danger" 
            c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id)}}"
            c-remove-closest="tr">
                Deletar
        </button>
    </td>
</tr>

templates/lista_clientes.html
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Lista de Clientes</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>

<body>

  <h1>Lista de Clientes</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista_clientes">

      {% for cliente in clientes %}
        {% include 'item_cliente.html' %}
      {% endfor %}

    </tbody>
  </table>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
    crossorigin="anonymous"></script>
</body>

</html>